server:
  port: 19091


spring:
  main:
    web-application-type: reactive  # Spring \uC560\uD50C\uB9AC\uCF00\uC774\uC158\uC774 \uB9AC\uC561\uD2F0\uBE0C \uC6F9 \uC560\uD50C\uB9AC\uCF00\uC774\uC158\uC73C\uB85C \uC124\uC815\uB428
  application:
    name: gateway  # \uC560\uD50C\uB9AC\uCF00\uC774\uC158 \uC774\uB984\uC744 'gateway'\uB85C \uC124\uC815
  cloud:
    gateway:
      routes: # Spring Cloud Gateway\uC758 \uB77C\uC6B0\uD305 \uC124\uC815
        - id: order  # \uB77C\uC6B0\uD2B8 \uC2DD\uBCC4\uC790
          uri: lb://order  # 'order'\uB77C\uB294 \uC774\uB984\uC73C\uB85C \uB85C\uB4DC \uBC38\uB7F0\uC2F1\uB41C \uC11C\uBE44\uC2A4\uB85C \uB77C\uC6B0\uD305
          predicates:
            - Path=/order/**  # /order/** \uACBD\uB85C\uB85C \uB4E4\uC5B4\uC624\uB294 \uC694\uCCAD\uC744 \uC774 \uB77C\uC6B0\uD2B8\uB85C \uCC98\uB9AC
        - id: product  # \uB77C\uC6B0\uD2B8 \uC2DD\uBCC4\uC790
          uri: lb://product  # 'product'\uB77C\uB294 \uC774\uB984\uC73C\uB85C \uB85C\uB4DC \uBC38\uB7F0\uC2F1\uB41C \uC11C\uBE44\uC2A4\uB85C \uB77C\uC6B0\uD305
          predicates:
            - Path=/product/**  # /product/** \uACBD\uB85C\uB85C \uB4E4\uC5B4\uC624\uB294 \uC694\uCCAD\uC744 \uC774 \uB77C\uC6B0\uD2B8\uB85C \uCC98\uB9AC
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
      discovery:
        locator:
          enabled: true  # \uC11C\uBE44\uC2A4 \uB514\uC2A4\uCEE4\uBC84\uB9AC\uB97C \uD1B5\uD574 \uB3D9\uC801\uC73C\uB85C \uB77C\uC6B0\uD2B8\uB97C \uC0DD\uC131\uD558\uB3C4\uB85D \uC124\uC815


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access-expiration: 3600000
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
